name: Validate JSONs

on:
  pull_request:
    branches:
      - main

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate JSON
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: src/schema.json
          jsons: src/data/*.json
