name: automerge

on:
  pull_request:
    branches:
      - main

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate JSON
        id: validate
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: schema.json
          jsons: data/*.json

      - name: Fail on JSON Validation Error
        if: steps.validate.outcome == 'failure'
        run: |
          echo "JSON validation failed. Halting workflow."
          exit 1


      - name: Add automerge label
        if: steps.validate.outcome == 'success'
        uses: actions/github-script@v5
        with:
          script: |
            const issue_number = context.payload.pull_request.number;
            console.log(`Adding labels to PR #${issue_number}`);
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              labels: ['automerge']
            }).then((response) => {
              console.log('Label added:', response.data);
            }).catch((error) => {
              console.error('Error adding label:', error);
              throw error;  // Ensure that the action fails on error
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  automerge:
    needs: verify-json-validation
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
